
export const BodyParts = [
  {
    id: 1,
    name: 'back',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/back2.jpg'),
  },
  {
    id: 2,
    name: 'cardio',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/cardio.jpg'),
  },
  {
    id: 3,
    name: 'chest',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/chests.jpg'),
  },
  {
    id: 4,
    name: 'lower arms',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/LowerArm.jpg'),
  },
  {
    id: 5,
    name: 'lower legs',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/lower_legs2.jpg'),
  },
  {
    id: 6,
    name: 'neck',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/wide-neck.jpg'),
  },
  {
    id: 7,
    name: 'shoulders',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/shoulders.jpg'),
  },
  {
    id: 8,
    name: 'upper arms',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/uppper_fore_Arms.webp'),
  },
  {
    id: 9,
    name: 'upper legs',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/upper_legs.jpg'),
  },
  {
    id: 10,
    name: 'waist',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/waist2.jpg'),
  },
];

export const Equipments = [
  {
    id: 1,
    name: 'band',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Bands.jpg'),
  },
  {
    id: 2,
    name: 'barbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/barbell.jpg'),
  },
  {
    id: 3,
    name: 'body weight',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/body_weight.jpg'),
  },
  {
    id: 4,
    name: 'bosu ball',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Bosu_ball.jpg'),
  },
  {
    id: 5,
    name: 'rope',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Rope.jpg'),
  },
  {
    id: 6,
    name: 'ez barbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Olmpyic barbell.jpg'),
  },
  {
    id: 7,
    name: 'cable',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Cable.jpg'),
  },
  {
    id: 8,
    name: 'dumbbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/dumbells.jpg'),
  },
  {
    id: 9,
    name: 'hammer',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Hammer.jpg'),
  },
  {
    id: 10,
    name: 'trap bar',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/TrapBar.jpg'),
  },
  {
    id: 11,
    name: 'weighted',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/weightedvest.jpg'),
  },
  {
    id: 12,
    name: 'kettlebell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/kettlebell.jpg'),
  },
  {
    id: 13,
    name: 'leverage machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/LeverageMachine.jpg'),
  },
  {
    id: 14,
    name: 'olympic barbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Olmpyic barbell.jpg'),
  },
  {
    id: 15,
    name: 'resistance band',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Bands.jpg'),
  },
  {
    id: 16,
    name: 'roller',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Rollers.jpeg'),
  },
  {
    id: 17,
    name: 'medicine ball',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/fitness_medicine_ball.jpg'),
  },
  {
    id: 18,
    name: 'sled machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/sledMachine.jpg'),
  },
  {
    id: 19,
    name: 'smith machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/smithMachine.jpg'),
  },
  {
    id: 20,
    name: 'elliptical machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Elliptical_Machine.jpg'),
  },
  {
    id: 21,
    name: 'stationary bike',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/stationaryBike.jpg'),
  },
  {
    id: 22,
    name: 'stepmill machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/stepMill.jpg'),
  },
  {
    id: 23,
    name: 'tire',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Tire.jpg'),
  },
];

export const restaurants = [
  {
    id: '1',
    name: 'Requiem of Pasta',
    category: 'Italian Dance',
    rating: 2,
    location: '123 Main St, Los Angeles, CA',
    phone: '(123) 456-7890',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/1/200/300?food',
    opening_hours: '10:00 AM - 10:00 PM',
    reviews: [
      {
        review_id: 101,
        user_id: 9,
        rating: 6,
        text: "Amazing pasta, the best I've ever had!",
        date: '2024-09-23',
      },
      {
        review_id: 102,
        user_id: 2,
        rating: 4,
        text: 'Great ambiance but the service was a bit slow.',
        date: '2024-09-22',
      },
    ],
  },
  {
    id: '2',
    name: 'Pasta Palace',
    category: 'Italian',
    rating: 4.5,
    location: '456 Main St, Los Angeles, CA',
    phone: '(123) 456-7890',
    price: '$$',
    image_url: 'https://picsum.photos/seed/2/200/300?food',
    opening_hours: '9:00 AM - 9:00 PM',
    reviews: [
      {
        review_id: 103,
        user_id: 1,
        rating: 5,
        text: "Amazing pasta, the best I've ever had!",
        date: '2024-09-23',
      },
    ],
  },
  {
    id: '3',
    name: 'Burger Barn',
    category: 'American',
    rating: 4,
    location: '789 Oak St, San Francisco, CA',
    phone: '(987) 654-3210',
    price: '$',
    image_url: 'https://picsum.photos/seed/3/200/300?food',
    opening_hours: '11:00 AM - 11:00 PM',
    reviews: [
      {
        review_id: 104,
        user_id: 3,
        rating: 4,
        text: 'Solid burgers, good price!',
        date: '2024-09-21',
      },
    ],
  },
  {
    id: '4',
    name: 'Pizza Paradise',
    category: 'Italian',
    rating: 4.2,
    location: '321 Elm St, New York, NY',
    phone: '(234) 567-8910',
    price: '$$',
    image_url: 'https://picsum.photos/seed/4/200/300?food',
    opening_hours: '10:00 AM - 11:00 PM',
    reviews: [
      {
        review_id: 105,
        user_id: 4,
        rating: 4,
        text: 'The pizza was great, loved the crust!',
        date: '2024-09-20',
      },
    ],
  },
  {
    id: '5',
    name: 'Taco Tower',
    category: 'Mexican',
    rating: 3.8,
    location: '1234 Pine St, Austin, TX',
    phone: '(345) 678-9101',
    price: '$',
    image_url: 'https://picsum.photos/seed/5/200/300?food',
    opening_hours: '8:00 AM - 8:00 PM',
    reviews: [
      {
        review_id: 106,
        user_id: 5,
        rating: 3,
        text: 'Tacos were okay, but the portions were small.',
        date: '2024-09-19',
      },
    ],
  },
  {
    id: '6',
    name: 'Sushi Spot',
    category: 'Japanese',
    rating: 4.7,
    location: '789 River St, Seattle, WA',
    phone: '(456) 789-0123',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/6/200/300?food',
    opening_hours: '11:00 AM - 10:00 PM',
    reviews: [],
  },
  {
    id: '7',
    name: 'BBQ Bliss',
    category: 'American',
    rating: 4.6,
    location: '123 Lake St, Dallas, TX',
    phone: '(567) 890-1234',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/7/200/300?food',
    opening_hours: '12:00 PM - 11:00 PM',
    reviews: [],
  },
  {
    id: '8',
    name: 'Dim Sum Delight',
    category: 'Chinese',
    rating: 4.3,
    location: '456 Forest St, San Diego, CA',
    phone: '(678) 901-2345',
    price: '$$',
    image_url: 'https://picsum.photos/seed/8/200/300?food',
    opening_hours: '10:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '9',
    name: 'The Curry Corner',
    category: 'Indian',
    rating: 4.8,
    location: '789 Bridge St, Boston, MA',
    phone: '(789) 012-3456',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/9/200/300?food',
    opening_hours: '12:00 PM - 10:00 PM',
    reviews: [],
  },
  {
    id: '10',
    name: 'Pho Paradise',
    category: 'Vietnamese',
    rating: 4.9,
    location: '321 Beach St, Miami, FL',
    phone: '(890) 123-4567',
    price: '$$',
    image_url: 'https://picsum.photos/seed/10/200/300?food',
    opening_hours: '9:00 AM - 8:00 PM',
    reviews: [],
  },
  {
    id: '11',
    name: 'Crepes & Cones',
    category: 'French',
    rating: 4.1,
    location: '100 Baker St, San Diego, CA',
    phone: '(901) 234-5678',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/11/200/300?food',
    opening_hours: '8:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '12',
    name: 'Tempura Temple',
    category: 'Japanese',
    rating: 4.5,
    location: '345 Sushi St, Seattle, WA',
    phone: '(123) 654-9876',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/12/200/300?food',
    opening_hours: '11:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '13',
    name: 'The Spicy Shack',
    category: 'Mexican',
    rating: 4.3,
    location: '234 Salsa Ln, Austin, TX',
    phone: '(432) 345-6789',
    price: '$',
    image_url: 'https://picsum.photos/seed/13/200/300?food',
    opening_hours: '7:00 AM - 8:00 PM',
    reviews: [],
  },
  {
    id: '14',
    name: 'Gourmet Grills',
    category: 'American',
    rating: 4.8,
    location: '456 BBQ St, Chicago, IL',
    phone: '(456) 789-0123',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/14/200/300?food',
    opening_hours: '12:00 PM - 11:00 PM',
    reviews: [],
  },
  {
    id: '15',
    name: 'Curry Quest',
    category: 'Indian',
    rating: 4.7,
    location: '123 Spice St, Boston, MA',
    phone: '(789) 012-3456',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/15/200/300?food',
    opening_hours: '11:00 AM - 10:00 PM',
    reviews: [],
  },
  {
    id: '16',
    name: 'Deli Delight',
    category: 'American',
    rating: 4.1,
    location: '789 Bagel Blvd, New York, NY',
    phone: '(890) 123-4567',
    price: '$',
    image_url: 'https://picsum.photos/seed/16/200/300?food',
    opening_hours: '6:00 AM - 6:00 PM',
    reviews: [],
  },
  {
    id: '17',
    name: 'Fusion Feast',
    category: 'Fusion',
    rating: 4.9,
    location: '123 Flavor St, Miami, FL',
    phone: '(123) 654-9876',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/17/200/300?food',
    opening_hours: '5:00 PM - 12:00 AM',
    reviews: [],
  },
  {
    id: '18',
    name: 'Vegan Vibes',
    category: 'Vegan',
    rating: 4.2,
    location: '234 Herb Ln, Portland, OR',
    phone: '(432) 345-6789',
    price: '$$',
    image_url: 'https://picsum.photos/seed/18/200/300?food',
    opening_hours: '9:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '19',
    name: 'Paella Palace',
    category: 'Spanish',
    rating: 4.6,
    location: '456 Valencia St, Los Angeles, CA',
    phone: '(456) 789-0123',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/19/200/300?food',
    opening_hours: '11:00 AM - 11:00 PM',
    reviews: [],
  },
  {
    id: '20',
    name: 'Tapas Town',
    category: 'Spanish',
    rating: 4.8,
    location: '789 Tapas St, San Francisco, CA',
    phone: '(789) 012-3456',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/20/200/300?food',
    opening_hours: '12:00 PM - 10:00 PM',
    reviews: [],
  },
];
// MEALS ARRAY - Individual dishes with real images and ratings
export const meals = [
    {
        id: '1',
        name: 'Classic Cheeseburger',
        category: 'American',
        rating: 4.5,
        price: '$12.99',
        image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
        description: 'Juicy beef patty with cheddar, lettuce, tomato, and special sauce',
        reviews: 342,
    },
    {
        id: '2',
        name: 'Margherita Pizza',
        category: 'Italian',
        rating: 4.8,
        price: '$16.00',
        image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
        description: 'Fresh mozzarella, tomato sauce, and basil on wood-fired crust',
        reviews: 567,
    },
    {
        id: '3',
        name: 'Chicken Tacos',
        category: 'Mexican',
        rating: 4.3,
        price: '$10.50',
        image_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
        description: 'Grilled chicken with fresh salsa, guacamole, and cilantro',
        reviews: 289,
    },
    {
        id: '4',
        name: 'Salmon Teriyaki',
        category: 'Japanese',
        rating: 4.7,
        price: '$22.99',
        image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
        description: 'Grilled salmon with teriyaki glaze, rice, and vegetables',
        reviews: 445,
    },
    {
        id: '5',
        name: 'Caesar Salad',
        category: 'Salads',
        rating: 4.1,
        price: '$11.99',
        image_url: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
        description: 'Crispy romaine, parmesan, croutons, and caesar dressing',
        reviews: 198,
    },
    {
        id: '6',
        name: 'Pad Thai',
        category: 'Thai',
        rating: 4.6,
        price: '$14.50',
        image_url: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400',
        description: 'Rice noodles with shrimp, peanuts, and tamarind sauce',
        reviews: 412,
    },
    {
        id: '7',
        name: 'BBQ Ribs',
        category: 'American',
        rating: 4.9,
        price: '$24.99',
        image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
        description: 'Slow-cooked baby back ribs with smoky BBQ sauce',
        reviews: 678,
    },
    {
        id: '8',
        name: 'Chicken Biryani',
        category: 'Indian',
        rating: 4.7,
        price: '$15.99',
        image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
        description: 'Fragrant basmati rice with spiced chicken and herbs',
        reviews: 523,
    },
    {
        id: '9',
        name: 'Sushi Platter',
        category: 'Japanese',
        rating: 4.8,
        price: '$28.00',
        image_url: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400',
        description: 'Assorted nigiri and rolls with wasabi and ginger',
        reviews: 612,
    },
    {
        id: '10',
        name: 'Beef Pho',
        category: 'Vietnamese',
        rating: 4.6,
        price: '$13.99',
        image_url: 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=400',
        description: 'Traditional Vietnamese soup with rice noodles and herbs',
        reviews: 387,
    },
    {
        id: '11',
        name: 'Fettuccine Alfredo',
        category: 'Italian',
        rating: 4.4,
        price: '$17.50',
        image_url: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=400',
        description: 'Creamy parmesan sauce with fresh fettuccine pasta',
        reviews: 299,
    },
    {
        id: '12',
        name: 'Fish and Chips',
        category: 'British',
        rating: 4.2,
        price: '$16.99',
        image_url: 'https://images.unsplash.com/photo-1579208575657-c595a05383b7?w=400',
        description: 'Beer-battered cod with crispy fries and tartar sauce',
        reviews: 234,
    },
    {
        id: '13',
        name: 'Greek Gyro',
        category: 'Greek',
        rating: 4.5,
        price: '$11.50',
        image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
        description: 'Lamb and beef with tzatziki, tomatoes, and onions in pita',
        reviews: 356,
    },
    {
        id: '14',
        name: 'Lobster Roll',
        category: 'Seafood',
        rating: 4.9,
        price: '$26.99',
        image_url: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?w=400',
        description: 'Fresh lobster meat with mayo in a toasted roll',
        reviews: 489,
    },
    {
        id: '15',
        name: 'Chicken Wings',
        category: 'American',
        rating: 4.3,
        price: '$13.99',
        image_url: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400',
        description: 'Crispy wings with buffalo sauce and blue cheese dip',
        reviews: 421,
    },
    {
        id: '16',
        name: 'Beef Bulgogi',
        category: 'Korean',
        rating: 4.7,
        price: '$19.99',
        image_url: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400',
        description: 'Marinated beef with rice, kimchi, and vegetables',
        reviews: 502,
    },
    {
        id: '17',
        name: 'Mushroom Risotto',
        category: 'Italian',
        rating: 4.6,
        price: '$18.50',
        image_url: 'https://images.unsplash.com/photo-1476124369491-c4cc9c31ba4a?w=400',
        description: 'Creamy arborio rice with mixed mushrooms and parmesan',
        reviews: 278,
    },
    {
        id: '18',
        name: 'Pulled Pork Sandwich',
        category: 'American',
        rating: 4.5,
        price: '$14.99',
        image_url: 'https://images.unsplash.com/photo-1619891270548-3f6f4f5b7e9f?w=400',
        description: 'Slow-cooked pork with coleslaw on brioche bun',
        reviews: 367,
    },
    {
        id: '19',
        name: 'Vegetable Curry',
        category: 'Indian',
        rating: 4.4,
        price: '$12.99',
        image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
        description: 'Mixed vegetables in aromatic curry sauce with naan',
        reviews: 312,
    },
    {
        id: '20',
        name: 'Chocolate Lava Cake',
        category: 'Dessert',
        rating: 4.9,
        price: '$8.99',
        image_url: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400',
        description: 'Warm chocolate cake with molten center and vanilla ice cream',
        reviews: 734,
    },
];
export const foodItems = [
     { name: "Drinks", icon: "coffee" },
    { name: "Smoothies", icon: "cup-water" },
    { name: "Pastries", icon: "cupcake" },
    { name: "Cake", icon: "cake" },
     ];
// EATERIES ARRAY - Restaurants and food chains with logos
export const eateries = [
    {
        id: '1',
        name: 'KFC',
        category: 'Fast Food',
        rating: 4.2,
        logo_url: 'https://logo.clearbit.com/kfc.com',
        location: 'Multiple Locations',
        phone: '1-800-CALL-KFC',
        opening_hours: '10:00 AM - 11:00 PM',
        specialty: 'Fried Chicken',
    },
    {
        id: '2',
        name: 'McDonalds',
        category: 'Fast Food',
        rating: 4.0,
        logo_url: 'https://logo.clearbit.com/mcdonalds.com',
        location: 'Multiple Locations',
        phone: '1-800-244-6227',
        opening_hours: '6:00 AM - 11:00 PM',
        specialty: 'Burgers & Fries',
    },
    {
        id: '3',
        name: 'Subway',
        category: 'Fast Food',
        rating: 3.9,
        logo_url: 'https://logo.clearbit.com/subway.com',
        location: 'Multiple Locations',
        phone: '1-800-888-4848',
        opening_hours: '7:00 AM - 10:00 PM',
        specialty: 'Sandwiches',
    },
    {
        id: '4',
        name: 'Pizza Hut',
        category: 'Pizza',
        rating: 4.1,
        logo_url: 'https://logo.clearbit.com/pizzahut.com',
        location: 'Multiple Locations',
        phone: '1-800-948-8488',
        opening_hours: '10:00 AM - 11:00 PM',
        specialty: 'Pizza & Wings',
    },
    {
        id: '5',
        name: 'Dominos',
        category: 'Pizza',
        rating: 4.3,
        logo_url: 'https://logo.clearbit.com/dominos.com',
        location: 'Multiple Locations',
        phone: '1-734-930-3030',
        opening_hours: '10:00 AM - 12:00 AM',
        specialty: 'Pizza Delivery',
    },
    {
        id: '6',
        name: 'Starbucks',
        category: 'Coffee',
        rating: 4.4,
        logo_url: 'https://logo.clearbit.com/starbucks.com',
        location: 'Multiple Locations',
        phone: '1-800-782-7282',
        opening_hours: '5:00 AM - 10:00 PM',
        specialty: 'Coffee & Pastries',
    },
    {
        id: '7',
        name: 'Chipotle',
        category: 'Mexican',
        rating: 4.3,
        logo_url: 'https://logo.clearbit.com/chipotle.com',
        location: 'Multiple Locations',
        phone: '1-303-595-4000',
        opening_hours: '10:45 AM - 10:00 PM',
        specialty: 'Burritos & Bowls',
    },
    {
        id: '8',
        name: 'Chick-fil-A',
        category: 'Fast Food',
        rating: 4.7,
        logo_url: 'https://logo.clearbit.com/chick-fil-a.com',
        location: 'Multiple Locations',
        phone: '1-866-232-2040',
        opening_hours: '6:00 AM - 10:00 PM',
        specialty: 'Chicken Sandwiches',
    },
    {
        id: '9',
        name: 'Taco Bell',
        category: 'Mexican',
        rating: 3.8,
        logo_url: 'https://logo.clearbit.com/tacobell.com',
        location: 'Multiple Locations',
        phone: '1-800-822-6235',
        opening_hours: '7:00 AM - 2:00 AM',
        specialty: 'Tacos & Burritos',
    },
    {
        id: '10',
        name: 'Wendys',
        category: 'Fast Food',
        rating: 4.1,
        logo_url: 'https://logo.clearbit.com/wendys.com',
        location: 'Multiple Locations',
        phone: '1-888-624-8140',
        opening_hours: '6:30 AM - 12:00 AM',
        specialty: 'Square Burgers',
    },
    {
        id: '11',
        name: 'Panera Bread',
        category: 'Bakery Cafe',
        rating: 4.2,
        logo_url: 'https://logo.clearbit.com/panerabread.com',
        location: 'Multiple Locations',
        phone: '1-855-372-6372',
        opening_hours: '6:00 AM - 9:00 PM',
        specialty: 'Soups & Sandwiches',
    },
    {
        id: '12',
        name: 'Dunkin',
        category: 'Coffee',
        rating: 4.0,
        logo_url: 'https://logo.clearbit.com/dunkindonuts.com',
        location: 'Multiple Locations',
        phone: '1-800-859-5339',
        opening_hours: '5:00 AM - 9:00 PM',
        specialty: 'Coffee & Donuts',
    },
    {
        id: '13',
        name: 'Burger King',
        category: 'Fast Food',
        rating: 3.9,
        logo_url: 'https://logo.clearbit.com/bk.com',
        location: 'Multiple Locations',
        phone: '1-866-394-2493',
        opening_hours: '6:00 AM - 12:00 AM',
        specialty: 'Flame-Grilled Burgers',
    },
    {
        id: '14',
        name: 'Five Guys',
        category: 'Burgers',
        rating: 4.5,
        logo_url: 'https://logo.clearbit.com/fiveguys.com',
        location: 'Multiple Locations',
        phone: '1-866-345-3897',
        opening_hours: '11:00 AM - 10:00 PM',
        specialty: 'Burgers & Fries',
    },
    {
        id: '15',
        name: 'Olive Garden',
        category: 'Italian',
        rating: 4.3,
        logo_url: 'https://logo.clearbit.com/olivegarden.com',
        location: 'Multiple Locations',
        phone: '1-800-331-2729',
        opening_hours: '11:00 AM - 10:00 PM',
        specialty: 'Italian Cuisine',
    },
    {
        id: '16',
        name: 'Applebees',
        category: 'American',
        rating: 3.8,
        logo_url: 'https://logo.clearbit.com/applebees.com',
        location: 'Multiple Locations',
        phone: '1-888-592-7753',
        opening_hours: '11:00 AM - 12:00 AM',
        specialty: 'American Grill',
    },
    {
        id: '17',
        name: 'IHOP',
        category: 'Breakfast',
        rating: 4.1,
        logo_url: 'https://logo.clearbit.com/ihop.com',
        location: 'Multiple Locations',
        phone: '1-866-444-5144',
        opening_hours: 'Open 24 Hours',
        specialty: 'Pancakes & Breakfast',
    },
    {
        id: '18',
        name: 'Buffalo Wild Wings',
        category: 'Sports Bar',
        rating: 4.2,
        logo_url: 'https://logo.clearbit.com/buffalowildwings.com',
        location: 'Multiple Locations',
        phone: '1-952-593-9943',
        opening_hours: '11:00 AM - 12:00 AM',
        specialty: 'Wings & Beer',
    },
    {
        id: '19',
        name: 'Red Lobster',
        category: 'Seafood',
        rating: 4.0,
        logo_url: 'https://logo.clearbit.com/redlobster.com',
        location: 'Multiple Locations',
        phone: '1-800-562-7837',
        opening_hours: '11:00 AM - 10:00 PM',
        specialty: 'Seafood & Lobster',
    },
    {
        id: '20',
        name: 'Texas Roadhouse',
        category: 'Steakhouse',
        rating: 4.5,
        logo_url: 'https://logo.clearbit.com/texasroadhouse.com',
        location: 'Multiple Locations',
        phone: '1-800-839-7623',
        opening_hours: '3:00 PM - 11:00 PM',
        specialty: 'Steaks & Ribs',
    },
];


export const AI_Image_API_Key = '';

export const secretKey = 'my_Super_Secret_Key_Here_Must_Not_Be_123, Or, Else';

 export const tokenGlobal ="";

//export const BaseURL = 'http://192.168.161.15:5151/Api';
 const url ="192.168.100.36";
export const BaseURL = `http://${url}:5151/Api`;
