// (NOBRIDGE) LOG  theeeeeeeeeeeese [{"bodyPart": "upper arms", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/UbptMUyu4L0yeC", "id": "0968",
// "instructions": ["Stand with your feet shoulder-width apart and hold the band with an underhand
//   grip, palms facing up.", "Keep your elbows close to your sides and slowly curl one arm up towards your shoulder, squeezing your biceps at the top.", "Lower the arm back down to the starting position and repeat with the other arm.", "Continue alternating arms for the desired number of repetitions."],
// "name": "band alternating biceps curl",
// "secondaryMuscles": ["forearms"], "target": "biceps"},
//
// {"bodyPart": "waist", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/jlPlRwQBuVepRU", "id":
//   "0969", "instructions": ["Lie flat on your back with your legs straight and your arms extended overhead, holding the band.", "Engage your abs and lift your legs and upper body off the ground simultaneously, reaching your hands towards your toes.", "As
//   you lower your legs and upper body back down, switch the position of your legs, crossing one over the other.", "Repeat the movement, alternating the position of your legs with each repetition.", "Continue for the desired number of repetitions."], "name": "band alternating v-up", "secondaryMuscles": ["hip flexors"], "target": "abs"}, {"bodyPart": "back", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/LzmAkJvn6HZIaX", "id": "0970", "instructions": ["Attach the band to a pull-up bar or
//   sturdy anchor point.", "Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.", "Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.", "Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.", "Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.", "Repeat for
//   the desired number of repetitions."],
//  "name": "band assisted pull-up",
// "secondaryMuscles": ["biceps", "forearms"], "target": "lats"},
//
// {"bodyPart": "waist", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/jOYq7L9rTIJ-lm", "id": "0971", "instructions": ["Kneel on the floor and hold the handles of the band with both hands, palms facing down.", "Place the band on the ground in front of you and position your hands shoulder-width apart.", "Engage your core and slowly roll the wheel forward, extending your body as far as you can while maintaining control.", "Pause for a moment at the furthest point, then slowly roll the wheel back towards your knees to return to the starting position.", "Repeat for the desired number of repetitions."], "name": "band assisted wheel rollerout", "secondaryMuscles": ["lower back"], "target": "abs"}, {"bodyPart": "waist", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/SnZJIwax4ybGgv", "id": "0972", "instructions": ["Lie flat on your back with your hands behind your head and your knees bent.", "Lift your feet off the ground and bring your right knee towards your chest while simultaneously twisting your torso to bring your left elbow towards your right knee.", "Straighten your right leg while bringing your left knee towards your chest and twisting your torso to bring your right elbow towards your left knee.", "Continue alternating the twisting motion, as if you are pedaling a bicycle, while keeping your core engaged throughout the movement.", "Repeat for the desired number of repetitions."], "name": "band bicycle crunch", "secondaryMuscles": ["hip flexors", "obliques"], "target": "abs"}, {"bodyPart": "back", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/kUuDu0aww7QsNS", "id": "0974", "instructions": ["Attach the band to a high anchor point, such as a pull-up bar or sturdy beam.", "Stand facing the anchor point and grab the band with an underhand grip, hands shoulder-width apart.", "Step back to create tension in the band, keeping your feet hip-width apart.", "Engage your core and keep your back straight as you pull the band down towards your chest, squeezing your shoulder blades together.", "Pause for a moment at the bottom of the movement, then slowly release the band back to the starting position.", "Repeat for the desired number of repetitions."], "name": "band close-grip pulldown", "secondaryMuscles": ["biceps", "forearms"], "target": "lats"}, {"bodyPart": "upper arms", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/uEwOQ5wLphQtVS", "id": "0975", "instructions": ["Place a band around your upper arms, just above the elbows.", "Assume a push-up position with your hands directly under your shoulders and your body in a straight line from head to heels.", "Bend your elbows and lower your chest towards the ground, keeping your elbows close to your sides.", "Push through your palms to extend your arms and return to the starting position.", "Repeat for the desired number of repetitions."], "name": "band close-grip push-up", "secondaryMuscles": ["chest", "shoulders"], "target": "triceps"}, {"bodyPart": "upper arms", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/KIS5E8TKk5pmUp", "id": "0976", "instructions": ["Sit on a bench or chair with your legs spread apart and your feet flat on the ground.", "Hold one end of the band in your hand and step on
//   the other end with your foot on the same side.", "Lean forward slightly and rest your elbow on the inside of your thigh, just
//   above the knee.", "With your palm facing up, slowly curl your hand towards your shoulder, keeping your upper arm stationary.", "Pause for a moment at the top, then slowly lower your hand back down to the starting position.", "Repeat for the desired number of repetitions, then switch sides."], "name": "band concentration curl", "secondaryMuscles": ["forearms"], "target": "biceps"}, {"bodyPart": "shoulders", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/1bU3v9FgZ2HLsv", "id": "0977",
//   "instructions": ["Stand with your feet shoulder-width apart and hold the band in front of your thighs with your palms facing down.", "Keep your arms straight and lift the band up in front of you until your arms are parallel to the ground.", "Pause for
//   a moment at the top, then slowly lower the band back down to the starting position.", "Repeat for the desired number of repetitions."], "name": "band front lateral raise", "secondaryMuscles": ["traps", "upper back"], "target": "delts"}, {"bodyPart": "shoulders", "equipment": "band", "gifUrl": "https://v2.exercisedb.io/image/0Pm5QB3aKBVDLg", "id": "0978", "instructions": ["Stand with your feet shoulder-width apart and hold the band in front of your thighs with your palms facing down.", "Keep your arms straight and slowly raise them forward until they are parallel to the ground.", "Pause for a moment at the top, then slowly
//   lower your arms back down to the starting position.", "Repeat for the desired number of repetitions."], "name": "band front raise", "secondaryMuscles": ["triceps", "upper back"], "target": "delts"}]

export const BodyParts = [
  {
    id: 1,
    name: 'back',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/back2.jpg'),
  },
  {
    id: 2,
    name: 'cardio',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/cardio.jpg'),
  },
  {
    id: 3,
    name: 'chest',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/chests.jpg'),
  },
  {
    id: 4,
    name: 'lower arms',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/LowerArm.jpg'),
  },
  {
    id: 5,
    name: 'lower legs',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/lower_legs2.jpg'),
  },
  {
    id: 6,
    name: 'neck',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/wide-neck.jpg'),
  },
  {
    id: 7,
    name: 'shoulders',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/shoulders.jpg'),
  },
  {
    id: 8,
    name: 'upper arms',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/uppper_fore_Arms.webp'),
  },
  {
    id: 9,
    name: 'upper legs',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/upper_legs.jpg'),
  },
  {
    id: 10,
    name: 'waist',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/waist2.jpg'),
  },
];

export const Equipments = [
  {
    id: 1,
    name: 'band',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Bands.jpg'),
  },
  {
    id: 2,
    name: 'barbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/barbell.jpg'),
  },
  {
    id: 3,
    name: 'body weight',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/body_weight.jpg'),
  },
  {
    id: 4,
    name: 'bosu ball',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Bosu_ball.jpg'),
  },
  {
    id: 5,
    name: 'rope',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Rope.jpg'),
  },
  {
    id: 6,
    name: 'ez barbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Olmpyic barbell.jpg'),
  },
  {
    id: 7,
    name: 'cable',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Cable.jpg'),
  },
  {
    id: 8,
    name: 'dumbbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/dumbells.jpg'),
  },
  {
    id: 9,
    name: 'hammer',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Hammer.jpg'),
  },
  {
    id: 10,
    name: 'trap bar',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/TrapBar.jpg'),
  },
  {
    id: 11,
    name: 'weighted',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/weightedvest.jpg'),
  },
  {
    id: 12,
    name: 'kettlebell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/kettlebell.jpg'),
  },
  {
    id: 13,
    name: 'leverage machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/LeverageMachine.jpg'),
  },
  {
    id: 14,
    name: 'olympic barbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Olmpyic barbell.jpg'),
  },
  {
    id: 15,
    name: 'resistance band',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Bands.jpg'),
  },
  {
    id: 16,
    name: 'roller',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Rollers.jpeg'),
  },
  {
    id: 17,
    name: 'medicine ball',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/fitness_medicine_ball.jpg'),
  },
  {
    id: 18,
    name: 'sled machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/sledMachine.jpg'),
  },
  {
    id: 19,
    name: 'smith machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/smithMachine.jpg'),
  },
  {
    id: 20,
    name: 'elliptical machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Elliptical_Machine.jpg'),
  },
  {
    id: 21,
    name: 'stationary bike',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/stationaryBike.jpg'),
  },
  {
    id: 22,
    name: 'stepmill machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/stepMill.jpg'),
  },
  {
    id: 23,
    name: 'tire',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Tire.jpg'),
  },
];

export const restaurants = [
  {
    id: '1',
    name: 'Requiem of Pasta',
    category: 'Italian Dance',
    rating: 2,
    location: '123 Main St, Los Angeles, CA',
    phone: '(123) 456-7890',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/1/200/300?food',
    opening_hours: '10:00 AM - 10:00 PM',
    reviews: [
      {
        review_id: 101,
        user_id: 9,
        rating: 6,
        text: "Amazing pasta, the best I've ever had!",
        date: '2024-09-23',
      },
      {
        review_id: 102,
        user_id: 2,
        rating: 4,
        text: 'Great ambiance but the service was a bit slow.',
        date: '2024-09-22',
      },
    ],
  },
  {
    id: '2',
    name: 'Pasta Palace',
    category: 'Italian',
    rating: 4.5,
    location: '456 Main St, Los Angeles, CA',
    phone: '(123) 456-7890',
    price: '$$',
    image_url: 'https://picsum.photos/seed/2/200/300?food',
    opening_hours: '9:00 AM - 9:00 PM',
    reviews: [
      {
        review_id: 103,
        user_id: 1,
        rating: 5,
        text: "Amazing pasta, the best I've ever had!",
        date: '2024-09-23',
      },
    ],
  },
  {
    id: '3',
    name: 'Burger Barn',
    category: 'American',
    rating: 4,
    location: '789 Oak St, San Francisco, CA',
    phone: '(987) 654-3210',
    price: '$',
    image_url: 'https://picsum.photos/seed/3/200/300?food',
    opening_hours: '11:00 AM - 11:00 PM',
    reviews: [
      {
        review_id: 104,
        user_id: 3,
        rating: 4,
        text: 'Solid burgers, good price!',
        date: '2024-09-21',
      },
    ],
  },
  {
    id: '4',
    name: 'Pizza Paradise',
    category: 'Italian',
    rating: 4.2,
    location: '321 Elm St, New York, NY',
    phone: '(234) 567-8910',
    price: '$$',
    image_url: 'https://picsum.photos/seed/4/200/300?food',
    opening_hours: '10:00 AM - 11:00 PM',
    reviews: [
      {
        review_id: 105,
        user_id: 4,
        rating: 4,
        text: 'The pizza was great, loved the crust!',
        date: '2024-09-20',
      },
    ],
  },
  {
    id: '5',
    name: 'Taco Tower',
    category: 'Mexican',
    rating: 3.8,
    location: '1234 Pine St, Austin, TX',
    phone: '(345) 678-9101',
    price: '$',
    image_url: 'https://picsum.photos/seed/5/200/300?food',
    opening_hours: '8:00 AM - 8:00 PM',
    reviews: [
      {
        review_id: 106,
        user_id: 5,
        rating: 3,
        text: 'Tacos were okay, but the portions were small.',
        date: '2024-09-19',
      },
    ],
  },
  {
    id: '6',
    name: 'Sushi Spot',
    category: 'Japanese',
    rating: 4.7,
    location: '789 River St, Seattle, WA',
    phone: '(456) 789-0123',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/6/200/300?food',
    opening_hours: '11:00 AM - 10:00 PM',
    reviews: [],
  },
  {
    id: '7',
    name: 'BBQ Bliss',
    category: 'American',
    rating: 4.6,
    location: '123 Lake St, Dallas, TX',
    phone: '(567) 890-1234',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/7/200/300?food',
    opening_hours: '12:00 PM - 11:00 PM',
    reviews: [],
  },
  {
    id: '8',
    name: 'Dim Sum Delight',
    category: 'Chinese',
    rating: 4.3,
    location: '456 Forest St, San Diego, CA',
    phone: '(678) 901-2345',
    price: '$$',
    image_url: 'https://picsum.photos/seed/8/200/300?food',
    opening_hours: '10:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '9',
    name: 'The Curry Corner',
    category: 'Indian',
    rating: 4.8,
    location: '789 Bridge St, Boston, MA',
    phone: '(789) 012-3456',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/9/200/300?food',
    opening_hours: '12:00 PM - 10:00 PM',
    reviews: [],
  },
  {
    id: '10',
    name: 'Pho Paradise',
    category: 'Vietnamese',
    rating: 4.9,
    location: '321 Beach St, Miami, FL',
    phone: '(890) 123-4567',
    price: '$$',
    image_url: 'https://picsum.photos/seed/10/200/300?food',
    opening_hours: '9:00 AM - 8:00 PM',
    reviews: [],
  },
  {
    id: '11',
    name: 'Crepes & Cones',
    category: 'French',
    rating: 4.1,
    location: '100 Baker St, San Diego, CA',
    phone: '(901) 234-5678',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/11/200/300?food',
    opening_hours: '8:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '12',
    name: 'Tempura Temple',
    category: 'Japanese',
    rating: 4.5,
    location: '345 Sushi St, Seattle, WA',
    phone: '(123) 654-9876',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/12/200/300?food',
    opening_hours: '11:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '13',
    name: 'The Spicy Shack',
    category: 'Mexican',
    rating: 4.3,
    location: '234 Salsa Ln, Austin, TX',
    phone: '(432) 345-6789',
    price: '$',
    image_url: 'https://picsum.photos/seed/13/200/300?food',
    opening_hours: '7:00 AM - 8:00 PM',
    reviews: [],
  },
  {
    id: '14',
    name: 'Gourmet Grills',
    category: 'American',
    rating: 4.8,
    location: '456 BBQ St, Chicago, IL',
    phone: '(456) 789-0123',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/14/200/300?food',
    opening_hours: '12:00 PM - 11:00 PM',
    reviews: [],
  },
  {
    id: '15',
    name: 'Curry Quest',
    category: 'Indian',
    rating: 4.7,
    location: '123 Spice St, Boston, MA',
    phone: '(789) 012-3456',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/15/200/300?food',
    opening_hours: '11:00 AM - 10:00 PM',
    reviews: [],
  },
  {
    id: '16',
    name: 'Deli Delight',
    category: 'American',
    rating: 4.1,
    location: '789 Bagel Blvd, New York, NY',
    phone: '(890) 123-4567',
    price: '$',
    image_url: 'https://picsum.photos/seed/16/200/300?food',
    opening_hours: '6:00 AM - 6:00 PM',
    reviews: [],
  },
  {
    id: '17',
    name: 'Fusion Feast',
    category: 'Fusion',
    rating: 4.9,
    location: '123 Flavor St, Miami, FL',
    phone: '(123) 654-9876',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/17/200/300?food',
    opening_hours: '5:00 PM - 12:00 AM',
    reviews: [],
  },
  {
    id: '18',
    name: 'Vegan Vibes',
    category: 'Vegan',
    rating: 4.2,
    location: '234 Herb Ln, Portland, OR',
    phone: '(432) 345-6789',
    price: '$$',
    image_url: 'https://picsum.photos/seed/18/200/300?food',
    opening_hours: '9:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '19',
    name: 'Paella Palace',
    category: 'Spanish',
    rating: 4.6,
    location: '456 Valencia St, Los Angeles, CA',
    phone: '(456) 789-0123',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/19/200/300?food',
    opening_hours: '11:00 AM - 11:00 PM',
    reviews: [],
  },
  {
    id: '20',
    name: 'Tapas Town',
    category: 'Spanish',
    rating: 4.8,
    location: '789 Tapas St, San Francisco, CA',
    phone: '(789) 012-3456',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/20/200/300?food',
    opening_hours: '12:00 PM - 10:00 PM',
    reviews: [],
  },
];

export const ExcerciseDB_API_KEY =
  'efbbf9641cmsh31c8cee6dcedda0p1ff29fjsn1e1c07bad08d';

export const AI_Image_API_Key = '';

export const secretKey = 'my_Super_Secret_Key_Here_Must_Not_Be_123, Or, Else';

 export const tokenGlobal ="";
     "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthaUBnbWFpbCIsIm5hbWVpZCI6ImI2NzQ1NWQwLWE4M2QtNDg3ZS1iMzE0LWFkNDUxYWYwODYzNiIsInVuaXF1ZV9uYW1lIjoia2FpIiwiZ2VuZGVyIjoic2hyZWQiLCJuYmYiOjE3NjE5NjA5MDMsImV4cCI6MTc2MTk4NjEwMywiaWF0IjoxNzYxOTUzNzAzfQ.NF1ylttnpIa0lRcSwcUA9u72EdBLn8vDXszAhK8Tqmo";

//export const BaseURL = 'http://192.168.161.15:5151/Api';
const local="127.0.0.1";
const url ="192.168.100.36";
export const BaseURL = `http://${url}:5151/Api`;
